stages:
  - build
  - deploy
  
build:
  stage: build
  script:
    - echo `pwd`
    - gradle clean build -x test

deploy:
  stage: deploy
  script:
    - echo `pwd`
    - gradle publishToMavenLocal

after_script:
  - echo "End CI"
